package io;

import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.junit.jupiter.api.Test;

import java.io.File;

import static org.junit.jupiter.api.Assertions.*;

/**
 * This is a test class that tests the I/O classes
 *
 * @author Jason Wang
 */
class InputReaderTest {
    /**
     * Tests if a node is successfully read from file.
     */
    @Test
    void testNode(){
        InputReader reader = new InputReader("try.dot");
        Graph g = reader.read();
        Node n = g.getNode("c");
        assertEquals(n.getAttribute("Weight"), 3.0);
    }

    /**
     * Tests if an edge is successfully read from file.
     */
    @Test
    void testEdge(){
        InputReader reader = new InputReader("try.dot");
        Graph g = reader.read();
        Edge e = g.getEdge("(a;e)");
        assertEquals(e.getAttribute("Weight"), 3.0);
    }

    /**
     * Tests if an output file can be generated by the output class.
     */
    @Test
    void testWrite(){
        InputReader reader = new InputReader("try.dot");
        Graph g = reader.read();
        OutputWriter writer = new OutputWriter();
        writer.write(g, "outputtry.dot");
        File dir = new File("outputtry.dot");
        assertTrue(dir.exists());
        removeOutput("outputtry.dot");
    }

    /**
     * Helper method to remove the testing file.
     * @param outputFileName file to be removed.
     */
    private void removeOutput(String outputFileName) {
        String filename = System.getProperty("user.dir") + System.getProperty("file.separator") + outputFileName;
        try{
            File file = new File(filename);
            if (!file.delete()){
                System.gc();
                file.delete();
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }
}